---
# Create Hash:
#   python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.encrypt(getpass.getpass()))"
#     <or>
#   mkpasswd  -m sha-512 -S $SALT                    | Replace $SALT with your salt
#     <or>
#   openssl passwd -1 -salt $SALT                    | Replace $SALT with your salt

- hosts: host
  tasks:
  - name: Change root password
    user: name=root update_password=always password=HASHGOESHERE
